version: '2.1'
services:
    redis:
        image: '172.16.0.183:8082/dcs/redis:5.0.5'
        # command: redis-server --requirepass redispass

    postgres:
        image: 172.16.0.183:8082/dcs/postgres:12.4
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
        # Uncomment these lines to persist data on the local filesystem.
        #     - PGDATA=/var/lib/postgresql/data/pgdata
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: 172.16.0.183:8082/dcs/docker-airflow:1.10.12-etl
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - C_FORCE_ROOT=True
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        #healthcheck:
        #    test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        #    interval: 30s
        #    timeout: 30s
        #    retries: 3

    flower:
        image: 172.16.0.183:8082/dcs/docker-airflow:1.10.12-etl
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - C_FORCE_ROOT=True
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: 172.16.0.183:8082/dcs/docker-airflow:1.10.12-etl
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - C_FORCE_ROOT=True
            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: 172.16.0.183:8082/dcs/docker-airflow:1.10.12-etl
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - C_FORCE_ROOT=True
            # - REDIS_PASSWORD=redispass
        command: worker
